spring.application.name=car-rental-system

server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=car_rental_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=testuser
spring.datasource.password=kush2811
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

app.jwt.secret=HTpgsrRhlmJIjpO/vmlFL53IbVT2P1+iQobNj9IiPkU=
app.jwt.expiration=86400000

spring.security.oauth2.client.registration.github.client-id=Ov23lizvhraXQeVo80cy
spring.security.oauth2.client.registration.github.client-secret=ca180356da28c0c10e442d7e472e73af6e783660
spring.security.oauth2.client.registration.github.scope=read:user,user:email
spring.security.oauth2.client.provider.github.user-name-attribute=login

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.rabbitmq.exchange=car-rental.exchange
app.rabbitmq.queue=car-rental.notifications
app.rabbitmq.routing-key=car-rental.notification
app.rabbitmq.booking.queue=car-rental.bookings
app.rabbitmq.booking.routing-key=car-rental.booking.created

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kushagrajuneja7@gmail.com
spring.mail.password=brji mtis gssw iyxb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
